---
# Dynamic inventory to fetch running RHEL instances
plugin: azure.azcollection.azure_rm

include_vm_resource_groups:
  - "*"

conditional_groups:
  all_the_hosts: true
  rhel_hosts: "'rhel' in name"
  windows_hosts: "'windows' in name"

# hostnames:
#   - tags.vm_name

keyed_groups:
  - prefix: tag
    key: tags
  - prefix: azure_loc
    key: location
  - prefix: os
    key: storageProfile.osDisk.osType

exclude_host_filters:
  # excludes hosts that are powered off
  - powerstate != 'running'
